### ISSUE TITLE
-32002 Error while trying to update metadata

### ISSUE THREAD

**Issue by shoxie** [samuelvanderwaal/metaboss#87]
### Versions

- Metaboss 0.4.1

### Description

I was trying to update my metadata with following command on devnet : 
```metaboss update data --account EKNHbvSnVtPytLKZkVdvJy7sdg2GGxW6aLKE6HkHBBPK --keypair key.json --new-data-file new.json --log-level trace```

My json file: 
```json
{
  "creators": [
    {
      "address": "WcWDVevYyx1XkWZSw1jiEwoY5yrbRepYizaZ7PMSxdb",
      "share": 0,
      "verified": true
    },
    {
      "address": "EKNHbvSnVtPytLKZkVdvJy7sdg2GGxW6aLKE6HkHBBPK",
      "share": 100,
      "verified": false
    }
  ],
  "name": "Madara",
  "seller_fee_basis_points": 250,
  "symbol": "skrt",
  "uri": "https://arweave.net/ECwOGn2AlhNnYNOZ8TSXsURyg-kVg5ISz-wUCf3NU04"
}
```

### Error 

Console print these after the command :

```[2022-02-14T03:27:02Z DEBUG reqwest::async_impl::client] response '200 OK' for https://api.devnet.solana.com/
[2022-02-14T03:27:02Z TRACE reqwest::blocking::wait] wait at most 90s
[2022-02-14T03:27:02Z TRACE want] signal: Want
[2022-02-14T03:27:02Z DEBUG solana_client::rpc_client] -32002 Transaction simulation failed: Error processing Instruction 0: Program failed to complete
[2022-02-14T03:27:02Z DEBUG solana_client::rpc_client]   1: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1]
[2022-02-14T03:27:02Z DEBUG solana_client::rpc_client]   2: Program log: (Deprecated as of 1.1.0) Instruction: Update Metadata Accounts
[2022-02-14T03:27:02Z DEBUG solana_client::rpc_client]   3: Program log: panicked at 'index out of bounds: the len is 0 but the index is 0', program/src/utils.rs:795:9
[2022-02-14T03:27:02Z DEBUG solana_client::rpc_client]   4: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 4929 of 200000 compute units
[2022-02-14T03:27:02Z DEBUG solana_client::rpc_client]   5: Program failed to complete: BPF program panicked
[2022-02-14T03:27:02Z DEBUG solana_client::rpc_client]   6: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: Program failed to complete
[2022-02-14T03:27:02Z DEBUG solana_client::rpc_client] 
[2022-02-14T03:27:02Z TRACE reqwest::blocking::client] closing runtime thread (ThreadId(2))
[2022-02-14T03:27:02Z TRACE reqwest::blocking::client] signaled close for runtime thread (ThreadId(2))
[2022-02-14T03:27:02Z TRACE reqwest::blocking::client] (ThreadId(2)) Receiver is shutdown
[2022-02-14T03:27:02Z TRACE reqwest::blocking::client] (ThreadId(2)) end runtime::block_on
[2022-02-14T03:27:02Z TRACE mio::poll] deregistering event source from poller
[2022-02-14T03:27:02Z TRACE want] signal: Closed
[2022-02-14T03:27:02Z TRACE reqwest::blocking::client] (ThreadId(2)) finished
[2022-02-14T03:27:02Z TRACE reqwest::blocking::client] closed runtime thread (ThreadId(2))
Error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: Program failed to complete [6 log messages]```

**Comment by shoxie** [comment]
Full log:
```
metaboss update data --account EKNHbvSnVtPytLKZkVdvJy7sdg2GGxW6aLKE6HkHBBPK --keypair key.json --new-data-file new.json --log-level trace
[2022-02-14T03:26:56Z WARN  metaboss] Using a public RPC URL is not recommended for heavy tasks as you will be rate-limited and suffer a performance hit.
            Please use a private RPC endpoint for best performance results.
[2022-02-14T03:26:56Z TRACE mio::poll] registering event source with poller: token=Token(0), interests=READABLE | WRITABLE
[2022-02-14T03:26:56Z TRACE reqwest::blocking::wait] (ThreadId(1)) park without timeout
[2022-02-14T03:26:56Z TRACE reqwest::blocking::client] (ThreadId(2)) start runtime::block_on
[2022-02-14T03:26:56Z TRACE reqwest::blocking::wait] wait at most 90s
[2022-02-14T03:26:56Z TRACE reqwest::blocking::wait] (ThreadId(1)) park timeout 89.999998127s
[2022-02-14T03:26:56Z DEBUG reqwest::connect] starting new connection: https://api.devnet.solana.com/
[2022-02-14T03:26:56Z TRACE mio::poll] registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
[2022-02-14T03:26:57Z TRACE want] signal: Want
[2022-02-14T03:26:57Z TRACE want] signal found waiting giver, notifying
[2022-02-14T03:26:57Z TRACE want] poll_want: taker wants!
[2022-02-14T03:26:58Z TRACE want] signal: Want
[2022-02-14T03:26:58Z TRACE want] signal: Want
[2022-02-14T03:26:58Z DEBUG reqwest::async_impl::client] response '200 OK' for https://api.devnet.solana.com/
[2022-02-14T03:26:58Z TRACE reqwest::blocking::wait] wait at most 90s
[2022-02-14T03:26:58Z TRACE want] signal: Want
[2022-02-14T03:26:58Z TRACE reqwest::blocking::wait] wait at most 90s
[2022-02-14T03:26:58Z TRACE reqwest::blocking::wait] (ThreadId(1)) park timeout 89.999998647s
[2022-02-14T03:26:58Z TRACE want] signal: Want
[2022-02-14T03:26:58Z TRACE want] signal: Want
[2022-02-14T03:26:58Z DEBUG reqwest::async_impl::client] response '200 OK' for https://api.devnet.solana.com/
[2022-02-14T03:26:58Z TRACE reqwest::blocking::wait] wait at most 90s
[2022-02-14T03:26:58Z TRACE want] signal: Want
[2022-02-14T03:26:58Z TRACE reqwest::blocking::wait] wait at most 90s
[2022-02-14T03:26:58Z TRACE reqwest::blocking::wait] (ThreadId(1)) park timeout 89.999998578s
[2022-02-14T03:26:59Z TRACE want] signal: Want
[2022-02-14T03:26:59Z TRACE want] signal: Want
[2022-02-14T03:26:59Z DEBUG reqwest::async_impl::client] response '200 OK' for https://api.devnet.solana.com/
[2022-02-14T03:26:59Z TRACE reqwest::blocking::wait] wait at most 90s
[2022-02-14T03:26:59Z TRACE want] signal: Want
[2022-02-14T03:26:59Z DEBUG solana_client::rpc_client] -32002 Transaction simulation failed: Error processing Instruction 0: Program failed to complete
[2022-02-14T03:26:59Z DEBUG solana_client::rpc_client]   1: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1]
[2022-02-14T03:26:59Z DEBUG solana_client::rpc_client]   2: Program log: (Deprecated as of 1.1.0) Instruction: Update Metadata Accounts
[2022-02-14T03:26:59Z DEBUG solana_client::rpc_client]   3: Program log: panicked at 'index out of bounds: the len is 0 but the index is 0', program/src/utils.rs:795:9
[2022-02-14T03:26:59Z DEBUG solana_client::rpc_client]   4: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 4929 of 200000 compute units
[2022-02-14T03:26:59Z DEBUG solana_client::rpc_client]   5: Program failed to complete: BPF program panicked
[2022-02-14T03:26:59Z DEBUG solana_client::rpc_client]   6: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: Program failed to complete
[2022-02-14T03:26:59Z DEBUG solana_client::rpc_client] 
[2022-02-14T03:26:59Z TRACE reqwest::blocking::wait] wait at most 90s
[2022-02-14T03:26:59Z TRACE reqwest::blocking::wait] (ThreadId(1)) park timeout 89.999997044s
[2022-02-14T03:26:59Z TRACE want] signal: Want
[2022-02-14T03:26:59Z TRACE want] signal: Want
[2022-02-14T03:26:59Z DEBUG reqwest::async_impl::client] response '200 OK' for https://api.devnet.solana.com/
[2022-02-14T03:26:59Z TRACE reqwest::blocking::wait] wait at most 90s
[2022-02-14T03:26:59Z TRACE want] signal: Want
[2022-02-14T03:26:59Z DEBUG solana_client::rpc_client] -32002 Transaction simulation failed: Error processing Instruction 0: Program failed to complete
[2022-02-14T03:26:59Z DEBUG solana_client::rpc_client]   1: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1]
[2022-02-14T03:26:59Z DEBUG solana_client::rpc_client]   2: Program log: (Deprecated as of 1.1.0) Instruction: Update Metadata Accounts
[2022-02-14T03:26:59Z DEBUG solana_client::rpc_client]   3: Program log: panicked at 'index out of bounds: the len is 0 but the index is 0', program/src/utils.rs:795:9
[2022-02-14T03:26:59Z DEBUG solana_client::rpc_client]   4: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 4929 of 200000 compute units
[2022-02-14T03:26:59Z DEBUG solana_client::rpc_client]   5: Program failed to complete: BPF program panicked
[2022-02-14T03:26:59Z DEBUG solana_client::rpc_client]   6: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: Program failed to complete
[2022-02-14T03:26:59Z DEBUG solana_client::rpc_client] 
[2022-02-14T03:27:00Z TRACE reqwest::blocking::wait] wait at most 90s
[2022-02-14T03:27:00Z TRACE reqwest::blocking::wait] (ThreadId(1)) park timeout 89.999997566s
[2022-02-14T03:27:00Z TRACE want] signal: Want
[2022-02-14T03:27:00Z TRACE want] signal: Want
[2022-02-14T03:27:00Z DEBUG reqwest::async_impl::client] response '200 OK' for https://api.devnet.solana.com/
[2022-02-14T03:27:00Z TRACE reqwest::blocking::wait] wait at most 90s
[2022-02-14T03:27:00Z TRACE want] signal: Want
[2022-02-14T03:27:00Z DEBUG solana_client::rpc_client] -32002 Transaction simulation failed: Error processing Instruction 0: Program failed to complete
[2022-02-14T03:27:00Z DEBUG solana_client::rpc_client]   1: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1]
[2022-02-14T03:27:00Z DEBUG solana_client::rpc_client]   2: Program log: (Deprecated as of 1.1.0) Instruction: Update Metadata Accounts
[2022-02-14T03:27:00Z DEBUG solana_client::rpc_client]   3: Program log: panicked at 'index out of bounds: the len is 0 but the index is 0', program/src/utils.rs:795:9
[2022-02-14T03:27:00Z DEBUG solana_client::rpc_client]   4: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 4929 of 200000 compute units
[2022-02-14T03:27:00Z DEBUG solana_client::rpc_client]   5: Program failed to complete: BPF program panicked
[2022-02-14T03:27:00Z DEBUG solana_client::rpc_client]   6: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: Program failed to complete
[2022-02-14T03:27:00Z DEBUG solana_client::rpc_client] 
[2022-02-14T03:27:01Z TRACE reqwest::blocking::wait] wait at most 90s
[2022-02-14T03:27:01Z TRACE reqwest::blocking::wait] (ThreadId(1)) park timeout 89.999996664s
[2022-02-14T03:27:02Z TRACE want] signal: Want
[2022-02-14T03:27:02Z TRACE want] signal: Want
[2022-02-14T03:27:02Z DEBUG reqwest::async_impl::client] response '200 OK' for https://api.devnet.solana.com/
[2022-02-14T03:27:02Z TRACE reqwest::blocking::wait] wait at most 90s
[2022-02-14T03:27:02Z TRACE want] signal: Want
[2022-02-14T03:27:02Z DEBUG solana_client::rpc_client] -32002 Transaction simulation failed: Error processing Instruction 0: Program failed to complete
[2022-02-14T03:27:02Z DEBUG solana_client::rpc_client]   1: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1]
[2022-02-14T03:27:02Z DEBUG solana_client::rpc_client]   2: Program log: (Deprecated as of 1.1.0) Instruction: Update Metadata Accounts
[2022-02-14T03:27:02Z DEBUG solana_client::rpc_client]   3: Program log: panicked at 'index out of bounds: the len is 0 but the index is 0', program/src/utils.rs:795:9
[2022-02-14T03:27:02Z DEBUG solana_client::rpc_client]   4: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 4929 of 200000 compute units
[2022-02-14T03:27:02Z DEBUG solana_client::rpc_client]   5: Program failed to complete: BPF program panicked
[2022-02-14T03:27:02Z DEBUG solana_client::rpc_client]   6: Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: Program failed to complete
[2022-02-14T03:27:02Z DEBUG solana_client::rpc_client] 
[2022-02-14T03:27:02Z TRACE reqwest::blocking::client] closing runtime thread (ThreadId(2))
[2022-02-14T03:27:02Z TRACE reqwest::blocking::client] signaled close for runtime thread (ThreadId(2))
[2022-02-14T03:27:02Z TRACE reqwest::blocking::client] (ThreadId(2)) Receiver is shutdown
[2022-02-14T03:27:02Z TRACE reqwest::blocking::client] (ThreadId(2)) end runtime::block_on
[2022-02-14T03:27:02Z TRACE mio::poll] deregistering event source from poller
[2022-02-14T03:27:02Z TRACE want] signal: Closed
[2022-02-14T03:27:02Z TRACE reqwest::blocking::client] (ThreadId(2)) finished
[2022-02-14T03:27:02Z TRACE reqwest::blocking::client] closed runtime thread (ThreadId(2))
Error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: Program failed to complete [6 log messages]
```

**Comment by shoxie** [comment]
I will mark this as solved as i find out that i didnt have permission to change metadata
